export const chapters = [
  { name: "Foundations", range: "Days 1-10", color: "#2bb9ff", icon: "◇" },
  { name: "n8n Builder", range: "Days 11-20", color: "#8d6bff", icon: "⌁" },
  { name: "Business Systems", range: "Days 21-30", color: "#24e4df", icon: "◎" },
  { name: "AI Agents", range: "Days 31-40", color: "#ff5fbd", icon: "✦" },
  { name: "RAG & Code", range: "Days 41-50", color: "#ffad3d", icon: "⌘" },
  { name: "Career Launch", range: "Days 51-60", color: "#8be35d", icon: "⚑" },
];

const rawDays = [
  ["Jun 15", "Set up workspace, LinkedIn, GitHub, roadmap"],
  ["Jun 16", "Intro to AI automation and prompt engineering"],
  ["Jun 17", "Prompt patterns and prompt library"],
  ["Jun 18", "API basics"],
  ["Jun 19", "REST APIs and HTTP methods"],
  ["Jun 20", "JSON fundamentals"],
  ["Jun 21", "Postman practice"],
  ["Jun 22", "Public API project"],
  ["Jun 23", "Webhooks"],
  ["Jun 24", "Mini project: FAQ assistant"],
  ["Jun 25", "Install and learn n8n"],
  ["Jun 26", "n8n triggers"],
  ["Jun 27", "n8n actions"],
  ["Jun 28", "Email automations"],
  ["Jun 29", "Google Sheets integrations"],
  ["Jun 30", "Forms to workflow"],
  ["Jul 1", "Multi-step workflow"],
  ["Jul 2", "Error handling"],
  ["Jul 3", "Project: Lead capture automation"],
  ["Jul 4", "Project polish + GitHub"],
  ["Jul 5", "CRM concepts"],
  ["Jul 6", "Lead qualification workflows"],
  ["Jul 7", "Email follow-up systems"],
  ["Jul 8", "Appointment booking flows"],
  ["Jul 9", "Business process mapping"],
  ["Jul 10", "Project: Dental clinic automation"],
  ["Jul 11", "Documentation"],
  ["Jul 12", "Portfolio update"],
  ["Jul 13", "AI agents introduction"],
  ["Jul 14", "Tool calling"],
  ["Jul 15", "Agent memory"],
  ["Jul 16", "Multi-agent concepts"],
  ["Jul 17", "Agent workflow design"],
  ["Jul 18", "Research agent build"],
  ["Jul 19", "Agent testing"],
  ["Jul 20", "Portfolio update"],
  ["Jul 21", "RAG fundamentals"],
  ["Jul 22", "Embeddings"],
  ["Jul 23", "Vector databases"],
  ["Jul 24", "Document ingestion"],
  ["Jul 25", "PDF chatbot build"],
  ["Jul 26", "Improve chatbot"],
  ["Jul 27", "SQL basics"],
  ["Jul 28", "JavaScript refresh"],
  ["Jul 29", "Git/GitHub polish"],
  ["Jul 30", "Resume draft"],
  ["Jul 31", "LinkedIn optimization"],
  ["Aug 1", "Mock interview 1"],
  ["Aug 2", "Mock interview 2"],
  ["Aug 3", "Apply to 20 jobs"],
  ["Aug 4", "Interview prep: APIs"],
  ["Aug 5", "Apply to 20 jobs"],
  ["Aug 6", "Interview prep: n8n"],
  ["Aug 7", "Apply to 20 jobs"],
  ["Aug 8", "Interview prep: agents"],
  ["Aug 9", "Apply to 20 jobs"],
  ["Aug 10", "Interview prep: projects"],
  ["Aug 11", "Apply to 20 jobs"],
  ["Aug 12", "Review weaknesses"],
  ["Aug 13", "Final portfolio + interview day"],
];

const dailyLearning = [
  "Set up your study system, project folders, progress tracker, and public profiles so every future task has a place to live.",
  "Learn what AI automation means, where prompts fit, and how automation connects tools, data, and repeatable business tasks.",
  "Study reusable prompt structures for role, context, constraints, examples, output format, and evaluation.",
  "Learn what APIs are, why apps expose them, and how requests and responses move data between systems.",
  "Study GET, POST, PUT, PATCH, DELETE, status codes, headers, query parameters, and request bodies.",
  "Learn JSON syntax, nested objects, arrays, keys, values, and how JSON becomes the shared language of automations.",
  "Practice sending API requests in Postman, saving collections, using environment variables, and reading responses.",
  "Learn how to choose a public API, read its docs, authenticate if needed, and turn response data into a tiny useful output.",
  "Study webhook triggers, payloads, callback URLs, and how event-based automation differs from polling.",
  "Learn how FAQ assistants match questions to answers, structure knowledge, and give helpful responses without overbuilding.",
  "Learn the n8n interface: workflows, nodes, credentials, executions, pinning data, and manual versus active runs.",
  "Study trigger nodes, schedules, webhooks, form triggers, and how automation starts from an event.",
  "Learn action nodes, field mapping, expressions, and how data flows from one node to the next.",
  "Study email automation patterns: templates, dynamic fields, send conditions, and reply-friendly formatting.",
  "Learn Google Sheets as a lightweight database for leads, tasks, logs, and automation status tracking.",
  "Study form intake patterns and how to turn submitted fields into clean workflow inputs.",
  "Learn how to chain triggers, filters, transforms, branches, and actions into one reliable multi-step workflow.",
  "Study error handling, retries, fallback paths, notifications, and how to inspect failed executions.",
  "Learn the full lead capture flow: collect a lead, validate details, store it, notify the team, and send confirmation.",
  "Study workflow cleanup, naming, screenshots, README notes, and how to present an automation project clearly.",
  "Learn CRM basics: contacts, companies, deals, pipelines, stages, activities, owners, and follow-up history.",
  "Study lead scoring rules, qualification questions, routing logic, and when a lead should become a sales opportunity.",
  "Learn follow-up sequences, timing, personalization fields, unsubscribe-safe language, and handoff points.",
  "Study appointment booking flows: availability, confirmations, reminders, cancellations, and calendar updates.",
  "Learn how to map business processes with inputs, actors, decisions, systems, outputs, and failure points.",
  "Study a dental clinic workflow from patient inquiry to appointment confirmation, reminders, and internal notes.",
  "Learn documentation habits: overview, setup steps, credentials needed, workflow diagram, testing notes, and known limits.",
  "Study portfolio storytelling: problem, solution, tools used, workflow screenshots, results, and what you would improve.",
  "Learn what AI agents are, how they use goals, tools, memory, planning, and feedback loops.",
  "Study tool calling: schemas, parameters, function results, guardrails, and when a model should call a tool.",
  "Learn short-term versus long-term memory, what to store, what to summarize, and how memory can go wrong.",
  "Study multi-agent patterns like planner-worker, researcher-writer, reviewer, and handoff workflows.",
  "Learn agent workflow design with clear goals, tool boundaries, stop conditions, logs, and evaluation criteria.",
  "Study how a research agent searches, filters sources, extracts facts, cites evidence, and creates a useful brief.",
  "Learn agent testing with fixed tasks, expected outputs, edge cases, failure analysis, and improvement notes.",
  "Study how to package your agent work as a portfolio update with demo steps, screenshots, and lessons learned.",
  "Learn RAG basics: retrieval, chunks, embeddings, vector search, context windows, and grounded generation.",
  "Study embeddings as numeric meaning representations and how similarity search finds related content.",
  "Learn vector database concepts: collections, metadata, indexes, top-k search, filtering, and retrieval quality.",
  "Study document ingestion: loading files, splitting text, cleaning content, metadata tagging, and storing chunks.",
  "Learn the PDF chatbot pipeline from upload to chunking, retrieval, prompt assembly, answer, and citation.",
  "Study improvement levers: chunk size, metadata filters, reranking, better prompts, and answer evaluation.",
  "Learn SQL fundamentals: tables, rows, columns, SELECT, WHERE, ORDER BY, LIMIT, and simple joins.",
  "Study JavaScript essentials for automation: variables, functions, arrays, objects, async calls, and JSON handling.",
  "Learn Git/GitHub polish: commits, repository structure, README quality, screenshots, and project links.",
  "Study resume positioning for AI automation roles, measurable bullets, project proof, and keyword alignment.",
  "Learn LinkedIn optimization: headline, about section, featured projects, skills, and outreach-friendly profile signals.",
  "Study interview storytelling with STAR answers, project walkthroughs, tradeoffs, and clear technical explanations.",
  "Practice answering unexpected questions by clarifying, structuring your thinking, and giving concrete examples.",
  "Learn job search batching: role filters, company notes, tailored bullets, application tracking, and follow-up timing.",
  "Review API interview concepts: authentication, methods, payloads, errors, rate limits, and debugging.",
  "Study how to keep applications focused while adjusting resume language to each role's responsibilities.",
  "Review n8n interview concepts: triggers, nodes, credentials, expressions, execution logs, and error handling.",
  "Learn how to compare job descriptions against your portfolio and choose the strongest project proof.",
  "Review agent interview concepts: tools, memory, evaluation, guardrails, planning, and practical limitations.",
  "Study outreach quality: concise messages, project links, role fit, and a simple follow-up schedule.",
  "Review project interview prep: problem framing, architecture, demo flow, metrics, failures, and improvements.",
  "Learn how to keep momentum during applications by tracking responses, interview stages, and next actions.",
  "Study your weak areas from mocks and projects, then turn each weakness into one targeted repair task.",
  "Learn how to present your final portfolio, walk through your best projects, and close interviews with confidence.",
];

const dailySteps = [
  [
    "Create a folder named AI Automation Roadmap with subfolders for notes, projects, screenshots, and portfolio assets.",
    "Update LinkedIn headline to: Aspiring AI Automation Specialist | n8n, APIs, AI Agents | Building 60 days in public.",
    "Update LinkedIn About with 3 short parts: what you are learning, what you are building, and what role you want.",
    "Create or clean GitHub, add a clear profile photo/name, and pin this roadmap repository if available.",
    "Write one public post: Today I started a 60-day AI automation roadmap. I will build real workflows and share proof.",
  ],
  [
    "Write a simple definition of AI automation in your notes: trigger, data, AI decision, action, and result.",
    "List 5 business tasks that repeat every day, such as lead replies, appointment reminders, and report summaries.",
    "For each task, write the trigger, input data, AI help needed, and final output.",
    "Pick one task that feels easiest and save it as your first automation idea.",
  ],
  [
    "Create a prompt library file with sections for role, goal, context, constraints, examples, and output format.",
    "Write 3 prompts: summarize a lead, rewrite an email, and extract action items from a message.",
    "Test each prompt once, then improve it by adding a clearer output format.",
    "Save the best version and write why it worked better.",
  ],
  [
    "Open notes and define client, server, endpoint, request, response, and API key in your own words.",
    "Visit a public API docs page and identify one endpoint, one method, and one example response.",
    "Draw the flow: your app sends request, API checks it, API sends response.",
    "Write one example of how an automation could use that API.",
  ],
  [
    "Make a table for GET, POST, PUT, PATCH, and DELETE with one real-world example for each.",
    "Write what status codes 200, 201, 400, 401, 403, 404, and 500 usually mean.",
    "Open Postman or browser dev tools and inspect headers on any request.",
    "Write the difference between query parameters and request body.",
  ],
  [
    "Create a sample JSON object for a new lead with name, email, phone, source, and message.",
    "Add a nested object for appointment preference and an array for tags.",
    "Paste the JSON into a validator and fix every syntax error.",
    "Write how this JSON could travel from a website form into a CRM.",
  ],
  [
    "Install or open Postman and create a workspace called AI Automation Practice.",
    "Send a GET request to a public API and save it in a collection.",
    "Add one query parameter, resend the request, and compare the response.",
    "Create an environment variable for a base URL and use it in the saved request.",
  ],
  [
    "Choose one public API that does not need paid access.",
    "Read its docs and copy one working endpoint into Postman.",
    "Create a tiny project note with API purpose, endpoint, inputs, response fields, and possible automation use.",
    "Save a screenshot of the successful response for your portfolio evidence.",
  ],
  [
    "Define webhook in one sentence: an app sends data to your URL when an event happens.",
    "Write 3 events that could trigger a webhook: form submitted, payment received, appointment booked.",
    "Sketch the payload fields you would expect from a lead form webhook.",
    "Write one risk to check, such as duplicate submissions or missing fields.",
  ],
  [
    "Create a small FAQ source with 10 questions and answers about one business.",
    "Write how the assistant should answer when it knows the answer and when it does not.",
    "Build or outline the simplest version: user question, matching answer, final response.",
    "Add screenshots, sample questions, and a README section explaining what it does.",
  ],
  [
    "Create an n8n account or open your local n8n instance.",
    "Explore the canvas, node search, credentials, executions, and workflow settings.",
    "Create a test workflow with a Manual Trigger and one Set/Edit Fields node.",
    "Run it once and save a screenshot of the execution output.",
  ],
  [
    "Create 3 tiny workflows, each starting with a different trigger type: manual, schedule, and webhook.",
    "For the schedule trigger, set it to run once per day and add a note about what it would automate.",
    "For the webhook trigger, copy the test URL and write what app could call it.",
    "Record which trigger type fits which business situation.",
  ],
  [
    "Add an action node after a trigger and map at least two fields from the incoming data.",
    "Use an expression to combine first name and last name into one full name field.",
    "Run the workflow with sample data and inspect the execution path.",
    "Write down the difference between fixed values and expressions.",
  ],
  [
    "Draft an email template for a new lead: greeting, acknowledgement, next step, and signature.",
    "Add dynamic fields for name, service interest, and appointment preference.",
    "Create a condition for missing name so the email still reads naturally.",
    "Test the template with two sample leads and save both outputs.",
  ],
  [
    "Create a Google Sheet with columns: date, name, email, phone, source, status, notes.",
    "Connect n8n to Google Sheets or write the exact credential steps if you cannot connect yet.",
    "Add a sample row from workflow data.",
    "Confirm the sheet can act as a simple lead database.",
  ],
  [
    "Create a form with name, email, phone, service needed, preferred date, and message.",
    "Write the expected JSON payload from that form.",
    "Map each form field to the columns in your Google Sheet.",
    "Add one validation rule: email required, phone required, or service required.",
  ],
  [
    "Design a 5-step workflow: trigger, clean data, save data, send email, notify owner.",
    "Add one if/else branch for high-value leads or missing information.",
    "Name every node clearly so a client could understand the workflow.",
    "Run one complete happy-path test and save the execution screenshot.",
  ],
  [
    "Break one workflow on purpose with missing data or a wrong field name.",
    "Open the failed execution and find the exact node that failed.",
    "Add a fallback path, error note, or notification step.",
    "Write a short debug checklist you can reuse later.",
  ],
  [
    "Build the lead capture workflow end to end: form/webhook input, clean fields, save lead, notify team, reply to lead.",
    "Test with one normal lead and one incomplete lead.",
    "Add a status field such as New, Contacted, or Needs Review.",
    "Create a project README with problem, tools, workflow steps, and screenshots.",
  ],
  [
    "Rename every workflow node with human-readable names.",
    "Add a short project summary to GitHub with setup notes and sample inputs.",
    "Add 2 screenshots: workflow canvas and successful execution.",
    "Write what you would improve if this were for a real client.",
  ],
  [
    "Create a CRM notes page defining contact, company, deal, pipeline, stage, owner, and activity.",
    "Open any CRM template or screenshot and identify those parts.",
    "Map your lead sheet columns to CRM fields.",
    "Write why businesses need follow-up history, not just a contact list.",
  ],
  [
    "Create 5 qualification questions for a lead, such as budget, timeline, need, location, and urgency.",
    "Assign points to each answer and define what score makes a lead qualified.",
    "Write one routing rule: hot leads notify owner immediately, warm leads enter follow-up.",
    "Test the scoring logic with 3 sample leads.",
  ],
  [
    "Write a 3-email follow-up sequence: instant reply, next-day helpful message, and final reminder.",
    "Add placeholders for name, service, booking link, and business name.",
    "Decide when the sequence should stop, such as booked appointment or replied.",
    "Save the sequence in your project notes.",
  ],
  [
    "Map the booking flow from lead request to confirmed appointment.",
    "List required fields: name, phone, service, preferred slot, confirmed slot, reminder status.",
    "Write messages for confirmation and reminder.",
    "Add cancellation or reschedule as an edge case.",
  ],
  [
    "Pick a small business process and write each step from customer action to final staff action.",
    "Mark each step as manual, automated, or AI-assisted.",
    "Find the slowest or most repetitive step.",
    "Rewrite the process with automation added only where it saves time.",
  ],
  [
    "Define the dental clinic intake flow: inquiry, qualification, appointment options, confirmation, reminder, staff note.",
    "Create the data fields needed for patient name, treatment, urgency, date preference, and contact method.",
    "Build or outline the automation with clear nodes and decision points.",
    "Test with urgent and non-urgent sample inquiries.",
  ],
  [
    "Write documentation sections: overview, tools, credentials, workflow steps, test cases, and limitations.",
    "Add exact setup steps someone else could follow.",
    "Include the sample input and expected output.",
    "Add screenshots next to the steps they explain.",
  ],
  [
    "Choose your strongest project so far.",
    "Write the portfolio story: problem, solution, workflow, tools, result, improvement ideas.",
    "Add 3 proof items: screenshot, sample output, and GitHub link.",
    "Update LinkedIn Featured or your README with the project link.",
  ],
  [
    "Define agent, tool, memory, goal, and observation in your own words.",
    "Write one example agent: research lead, summarize company, draft outreach email.",
    "Identify which parts need AI and which parts are normal automation.",
    "Write one danger of agents, such as making unsupported claims.",
  ],
  [
    "Write a simple tool schema with name, purpose, inputs, and output.",
    "Choose 3 tools an agent could use: search, calculator, database lookup.",
    "Write when the agent should call each tool.",
    "Add one guardrail: do not call a tool without required inputs.",
  ],
  [
    "List what should be remembered about a user or lead and what should never be stored.",
    "Separate temporary context from long-term profile information.",
    "Write a memory update rule in plain English.",
    "Add one privacy note about sensitive data.",
  ],
  [
    "Draw a planner-worker-reviewer flow for a research task.",
    "Define the job of each agent in one sentence.",
    "Write the handoff format between agents.",
    "Add a final reviewer checklist for accuracy and usefulness.",
  ],
  [
    "Pick one agent workflow and write the goal, inputs, tools, stop condition, and final output.",
    "Add a failure path for missing data or tool errors.",
    "Write 3 test prompts that should produce predictable results.",
    "Save the workflow design before building.",
  ],
  [
    "Build or outline a research agent that takes a company name and returns a short briefing.",
    "Define the sections: company summary, target customer, recent signal, outreach angle.",
    "Require the agent to separate facts from assumptions.",
    "Save one sample output and review it manually.",
  ],
  [
    "Create 5 test cases for your agent, including one easy, one vague, and one impossible request.",
    "Score each output for accuracy, usefulness, format, and safety.",
    "Improve the prompt or workflow based on the worst score.",
    "Write a short before/after note.",
  ],
  [
    "Package the agent project with title, problem, workflow diagram, sample input, sample output, and limitations.",
    "Add one screenshot of the agent running.",
    "Add one paragraph explaining what makes it useful for a business.",
    "Publish or save the project link in your portfolio tracker.",
  ],
  [
    "Define RAG as retrieve relevant information, add it to the prompt, then generate an answer.",
    "Write why RAG is better than pasting a whole document into a prompt.",
    "List the pieces: documents, chunks, embeddings, vector database, retriever, answer prompt.",
    "Sketch the PDF chatbot flow.",
  ],
  [
    "Explain embeddings as numbers that represent meaning.",
    "Write 5 similar phrases and 5 unrelated phrases to understand similarity search.",
    "Note what makes retrieval fail: bad chunks, missing metadata, or vague questions.",
    "Write where embeddings fit in your chatbot pipeline.",
  ],
  [
    "Define collection, document, metadata, index, top-k, and filter.",
    "Choose a vector database option to learn first.",
    "Write what metadata you would store for PDF chunks: file name, page, section, source.",
    "Design one query with and without a metadata filter.",
  ],
  [
    "Choose one PDF or document for your chatbot.",
    "Split it into logical chunks and name each chunk with page or section metadata.",
    "Remove junk text such as headers, footers, or repeated navigation if present.",
    "Write 5 questions the document should answer.",
  ],
  [
    "Build or outline the PDF chatbot pipeline: upload, extract text, chunk, embed, store, retrieve, answer.",
    "Create a prompt that says answer only from the provided context.",
    "Ask the 5 questions from yesterday and mark which answers are grounded.",
    "Save screenshots and one sample transcript.",
  ],
  [
    "Improve retrieval by changing chunk size, adding metadata, or asking clearer questions.",
    "Add a fallback answer for when the document does not contain the answer.",
    "Compare before and after answers for 3 questions.",
    "Write one improvement you would make in production.",
  ],
  [
    "Create a small table on paper or in a database with leads and statuses.",
    "Write SELECT queries for all rows, filtered rows, sorted rows, and limited rows.",
    "Write one join example using leads and appointments.",
    "Save your query examples in notes.",
  ],
  [
    "Review variables, arrays, objects, functions, map, filter, and async/await.",
    "Write a JavaScript function that cleans a lead object.",
    "Write another function that formats an email message from that object.",
    "Run or mentally trace the code with two sample inputs.",
  ],
  [
    "Clean your GitHub project names, README files, screenshots, and descriptions.",
    "Make sure each project explains the problem before the tools.",
    "Add install/setup notes only if someone else needs them.",
    "Pin your best 3 projects on GitHub.",
  ],
  [
    "Create a resume section called Projects with 3 automation projects.",
    "Write each bullet as Built X using Y to achieve Z.",
    "Add tools keywords naturally: n8n, APIs, webhooks, Google Sheets, AI agents, RAG.",
    "Remove vague claims that do not have proof.",
  ],
  [
    "Update LinkedIn headline, About, Featured, Skills, and Experience/Projects.",
    "Add your best project link to Featured.",
    "Write 5 skills that match the jobs you want.",
    "Post one short project update with screenshot and lesson learned.",
  ],
  [
    "Pick one project and prepare a 2-minute walkthrough.",
    "Answer: what problem did it solve, what did you build, what failed, what did you improve.",
    "Record yourself once or write the answer out loud.",
    "Fix the answer so it sounds clear and specific.",
  ],
  [
    "Choose 10 common interview questions and write short bullet answers.",
    "Practice one question you did not prepare by using this structure: clarify, think, answer, example.",
    "Review your weakest technical topic from the roadmap.",
    "Write 3 follow-up questions to ask an interviewer.",
  ],
  [
    "Find 20 roles using keywords like AI Automation, n8n, Workflow Automation, Automation Specialist, and AI Operations.",
    "For each role, record company, link, required tools, and one matching project.",
    "Tailor the top 3 resume bullets to the role.",
    "Apply and log the date, version of resume, and follow-up date.",
  ],
  [
    "Review API concepts: methods, status codes, auth, headers, payloads, webhooks, and rate limits.",
    "Explain one API project from your portfolio in plain English.",
    "Prepare answers for how you debug a failed API request.",
    "Add any weak API topic to your review list.",
  ],
  [
    "Apply to 20 more roles, but skip roles where you cannot explain your fit.",
    "Customize your opening summary or cover note with one relevant project.",
    "Track every application in your sheet.",
    "Send 3 respectful connection messages to people at target companies.",
  ],
  [
    "Review n8n concepts: triggers, actions, credentials, expressions, executions, branches, and errors.",
    "Open one workflow and practice explaining every node.",
    "Prepare answers for what you would monitor in production.",
    "Write one example of a workflow you could build for a client.",
  ],
  [
    "Apply to 20 roles and attach or mention your most relevant automation project when possible.",
    "Use your tracker to avoid duplicate applications.",
    "Mark roles that mention APIs, CRM, agents, or RAG.",
    "Write one sentence after each application explaining why you fit.",
  ],
  [
    "Review agent concepts: goal, tools, memory, guardrails, evaluation, and limitations.",
    "Explain your research agent or designed agent workflow.",
    "Prepare one answer about preventing hallucinations.",
    "Prepare one answer about testing agent output quality.",
  ],
  [
    "Apply to 20 roles and send 5 focused follow-ups or recruiter messages.",
    "Keep each message under 5 sentences and include one project link.",
    "Update your tracker with message date and next follow-up date.",
    "Review which job titles are responding best.",
  ],
  [
    "Pick your 3 best projects and create a 60-second explanation for each.",
    "Prepare screenshots in the order you will show them.",
    "Write tradeoffs: why you chose that tool, what you skipped, and what you would improve.",
    "Practice moving from problem to demo to result without rambling.",
  ],
  [
    "Apply to 20 roles and prioritize companies where your projects match their workflows.",
    "Improve one resume bullet based on the strongest job description you saw.",
    "Update your tracker and mark roles needing follow-up.",
    "Spend 15 minutes reviewing previous rejection or no-response patterns.",
  ],
  [
    "Review your notes, mocks, and project gaps.",
    "Choose the top 3 weak areas and write one repair task for each.",
    "Fix one portfolio or resume weakness immediately.",
    "Create a final interview cheat sheet with projects, tools, stories, and questions.",
  ],
  [
    "Finalize GitHub, LinkedIn, resume, and project screenshots.",
    "Open each project link and confirm it works.",
    "Practice your intro, best project walkthrough, and closing question.",
    "End with a written plan for the next 7 days of applications and interviews.",
  ],
];

export const videos = {
  prompt: {
    id: "_ZvnD73m40o",
    title: "Prompt Engineering Tutorial",
    creator: "freeCodeCamp.org",
    length: "Full course",
  },
  api: {
    id: "WXsD0ZgxjRw",
    title: "APIs for Beginners",
    creator: "freeCodeCamp.org",
    length: "Full course",
  },
  n8n: {
    id: "4BVTkqbn_tY",
    title: "n8n Beginner Course",
    creator: "n8n",
    length: "Official series",
  },
  agents: {
    id: "OhI005_aJkA",
    title: "AI Agents for Beginners",
    creator: "Microsoft Developer",
    length: "Lessons 1-10",
  },
  rag: {
    id: "mHxLXzYjQRE",
    title: "Production RAG with Vector Databases",
    creator: "freeCodeCamp.org",
    length: "Full course",
  },
  code: {
    id: "jS4aFq5-91M",
    title: "JavaScript Programming",
    creator: "freeCodeCamp.org",
    length: "Full course",
  },
  git: {
    id: "8JJ101D3knE",
    title: "Git Tutorial for Beginners",
    creator: "Programming with Mosh",
    length: "1 hour",
  },
  resume: {
    id: "Tt08KmFfIYQ",
    title: "Write an Incredible Resume",
    creator: "Jeff Su",
    length: "Practical guide",
  },
  interview: {
    id: "ZqNorUIgIe8",
    title: "Answer Questions You Didn't Prepare For",
    creator: "Jeff Su",
    length: "Interview guide",
  },
  apiRest: {
    id: "TnUn_XLh2ps",
    title: "Learn REST APIs the Easy Way with Postman",
    creator: "JavaScript Mastery",
    length: "Focused tutorial",
  },
  postman: {
    id: "BBQrv8RAG0Y",
    title: "API Testing Using Postman: Complete Crash Course",
    creator: "freeCodeCamp.org",
    length: "Crash course",
  },
  n8nFull: {
    id: "GIZzRGYpCbM",
    title: "n8n Course for Beginners",
    creator: "freeCodeCamp.org",
    length: "Full course",
  },
  n8nWebhooks: {
    id: "Qa0UZyS00MQ",
    title: "How to Master n8n Webhooks",
    creator: "Aurelius Tjin",
    length: "Step-by-step",
  },
  n8nAi: {
    id: "GuaKeDS6UKU",
    title: "n8n AI Agent Tutorial for Beginners",
    creator: "AI automation tutorial",
    length: "Project tutorial",
  },
  workflow: {
    id: "iWFAykxJh94",
    title: "Webhook to AI Agent to Google Sheets",
    creator: "AI automation tutorial",
    length: "Workflow build",
  },
  linkedin: {
    id: "OKF7ZeWNrfg",
    title: "Top LinkedIn Profile Tips",
    creator: "Jeff Su",
    length: "10 minutes",
  },
  linkedinProfile: {
    id: "qfL4K_afFRE",
    title: "How to Optimize Every Section of Your Profile",
    creator: "LinkedIn profile guide",
    length: "Profile walkthrough",
  },
  agenticRag: {
    id: "ix3c2KQFMgQ",
    title: "Agentic RAG, Open LLMs, Free Embeddings",
    creator: "Alejandro AO",
    length: "Recent tutorial",
  },
};

const dailyVideoIds = [
  "AJocoZEV7ew",
  "4BVTkqbn_tY",
  "2BpCk4d2Cc0",
  "WXsD0ZgxjRw",
  "TnUn_XLh2ps",
  "LzOtbUw6f_o",
  "MFxk5BZulVU",
  "FjgYtQK_zLE",
  "wdLvXKkXhLk",
  "_ZvnD73m40o",
  "e3OV3LnrS7o",
  "4cQWJViybAQ",
  "GIZzRGYpCbM",
  "Z3Umqpb_10E",
  "EXm_IsINLbg",
  "uFc7YQG0a1M",
  "iWFAykxJh94",
  "W0jeimUjOuY",
  "lK3veuZAg0c",
  "GMLCgiOzTyU",
  "0C9XIhvFk64",
  "9QtFwPSLxbw",
  "FE5yzAYQmaw",
  "EQsAy08B1uI",
  "nRqrXl3SzIA",
  "j1wRgyPVkzk",
  "IWzDlKSfN00",
  "e_ZcfAYulBE",
  "OhI005_aJkA",
  "MZhjki7t6p8",
  "EsTrWCV0Ph4",
  "CnXdddeZ4tQ",
  "aijS9fWB854",
  "GuaKeDS6UKU",
  "RTKHGlEOhkY",
  "lFKsx_8Pv9c",
  "_HQ2H_0Ayy0",
  "9iGvXxH_fdE",
  "mHxLXzYjQRE",
  "MykcjWPJ6T4",
  "2TJxpyO3ei4",
  "SXjfAIwbkZY",
  "p3qvj9hO_Bo",
  "jS4aFq5-91M",
  "RGOj5yH7evk",
  "Tt08KmFfIYQ",
  "qfL4K_afFRE",
  "ZqNorUIgIe8",
  "QrmDmQ7ZivM",
  "L5OmrG7z44c",
  "-mN3VyJuCjM",
  "lq8OaM-SeJo",
  "jCWPqTDgplk",
  "PPGRUQXQxpo",
  "Zqno_vux6d8",
  "dQ6RNltrXro",
  "eBq2EN6tqmY",
  "TEIzybC99Lg",
  "IW472-d_8bs",
  "NcD3nufvA7Y",
];

function videoForDay(day, stepIndex = 0) {
  const id = dailyVideoIds[(day - 1 + stepIndex * 13) % dailyVideoIds.length];
  return {
    id,
    url: `https://www.youtube.com/watch?v=${id}`,
  };
}

function objectivesFor(title, day) {
  if (title.includes("Project") || title.includes("project") || title.includes("build")) {
    return [
      "Define the input, output, and success criteria",
      "Build the smallest working version",
      "Test one happy path and one failure path",
      "Capture a screenshot and add notes to GitHub",
    ];
  }
  if (title.includes("Apply")) {
    return [
      "Shortlist roles that match your current skills",
      "Tailor your top resume bullets",
      "Send 20 focused applications",
      "Track every application and follow-up date",
    ];
  }
  if (day === 1) {
    return [
      "Create a focused learning workspace",
      "Optimize your LinkedIn headline",
      "Create or clean up your GitHub profile",
      "Read the full roadmap and protect your study time",
    ];
  }
  return [
    `Learn the core idea behind ${title.toLowerCase()}`,
    "Take concise notes in your own words",
    "Complete one hands-on exercise",
    "Write down one interview question and answer",
  ];
}

export const days = rawDays.map(([date, title], index) => {
  const number = index + 1;
  return {
    number,
    date,
    title,
    chapter: Math.floor(index / 10),
    xp: title.toLowerCase().includes("project") || title.toLowerCase().includes("apply") ? 100 : 50,
    learning: dailyLearning[index],
    steps: dailySteps[index].map((step, stepIndex) => ({
      text: step,
      video: videoForDay(number, stepIndex),
    })),
    objectives: objectivesFor(title, number),
    video: videoForDay(number),
  };
});

export const projects = [
  { day: 10, name: "FAQ Assistant", color: "#2bb9ff" },
  { day: 19, name: "Lead Capture Automation", color: "#8d6bff" },
  { day: 26, name: "Dental Clinic Automation", color: "#24e4df" },
  { day: 34, name: "Research Agent", color: "#ff5fbd" },
  { day: 41, name: "PDF Chatbot", color: "#ffad3d" },
];

export const achievements = [
  { at: 1, name: "Ignition", detail: "Complete Day 1" },
  { at: 10, name: "First Build", detail: "Complete Day 10" },
  { at: 20, name: "Workflow Builder", detail: "Complete Day 20" },
  { at: 30, name: "Systems Thinker", detail: "Complete Day 30" },
  { at: 40, name: "Agent Maker", detail: "Complete Day 40" },
  { at: 50, name: "Code Master", detail: "Complete Day 50" },
  { at: 60, name: "Career Ready", detail: "Complete Day 60" },
];
